<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/hello.proto

namespace GPBMetadata\Proto;

class Hello
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a99010a1170726f746f2f68656c6c6f2e70726f746f221c0a0c48656c6c6f52657175657374120c0a046e616d6518012001280922200a0d48656c6c6f526573706f6e7365120f0a076d65737361676518012001280932340a0548656c6c6f122b0a0853617948656c6c6f120d2e48656c6c6f526571756573741a0e2e48656c6c6f526573706f6e7365220042065a042e2f7062620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

